language: java

jobs:
  include:
    - jdk: openjdk8
      dist: trusty
    - jdk: oraclejdk8
      dist: trusty
    - jdk: openjdk11
      dist: bionic
    - jdk: openjdk13
      dist: bionic
    - jdk: oraclejdk11
      dist: bionic

os: linux
group: stable

cache:
  directories:
  - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)