language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk13
  - oraclejdk8
  - oraclejdk11

os: linux
dist: bionic
group: stable

cache:
  directories:
  - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)