version: 0.{branch}.{build}
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk11
install:
- cmd: SET PATH=%JAVA_HOME%\bin;%PATH%;
build_script:
- cmd: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
test_script:
- cmd: mvn test -B
notifications:
- provider: Email
  to:
  - slawomir.chodnicki@twineworks.com
  subject: AppVeyor build status
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
cache:
  - '%USERPROFILE%\.m2 -> appveyor.yml'